#!/bin/bash

coin=${coin:-LTC}
amount=${amount:-50}
#rub=${rub:-1}
#get=${get:-1}

while [ $# -gt 0 ]; do

   if [[ $1 == *"--"* ]]; then
        param="${1/--/}"
        declare "$param"="$2"
   fi

  shift
done

coin=$(echo "$coin" | tr '[:lower:]' '[:upper:]')

rate=$(curl -s api.bitbase.es/coins/"$coin" | jq '.price')
sell_commission=1.1111111
buy_commission=1.098

echo ""
echo "+--------+--------------------"
date +"| date   | %Y.%m.%d"
date +"| time   | %T"
echo "+--------+--------------------"
echo "| coin   | $coin"
echo "| rate   | $rate eur"
if [ -n "$rub" ] &&  [ -n "$get" ];
then
  echo "$rub" "$get" "$amount" | awk '{print "| rate   | "  $1/$2/$3 " rub"}'
fi
echo "+--------+--------------------"
echo "| amount | $amount"
echo "+--------+--------------------"
echo "$rate" "$sell_commission" | awk '{print "| buy    | " $1*$2 " eur"}'
echo "$amount" "$rate" "$sell_commission" | awk '{print "| get    | "  $1/$2/$3}'
echo "+--------+--------------------"
echo "$rate" "$sell_commission" | awk '{print "| sell   | " $1/$2 " eur"}'
echo "$amount" "$rate" "$sell_commission" | awk '{print "| get    | "  $1/$2*$3}'
echo "+--------+--------------------"
