#!/bin/bash

coin=${coin:-LTC}
amount=${amount:-1}
# E - Efectivo, T - Transferencia, TG - buys with Tarjeta
how=${how:-E}

while [ $# -gt 0 ]; do

   if [[ $1 == *"--"* ]]; then
        param="${1/--/}"
        declare "$param"="$2"
   fi

  shift
done

coin=$(echo "$coin" | tr '[:lower:]' '[:upper:]')

# Get current count rate
rate=$(curl -s api.bitbase.es/coins/"$coin" | jq '.price')

# Raw commissions
raw_fee=$(cat ./fee/"$coin".json)

# Commissions for money transfer path
fee=$(echo "$raw_fee" | jq '.'"$how")

commission=$(echo "$fee"| awk '{print 1-$1}')

buy_rate=$(echo "$rate" "$commission" | awk '{print $1*$2}')
buy_coin=$(echo "$amount" "$commission" "$rate" | awk '{print $1*$2/$3}')
sell_rate=$(echo "$rate" "$commission" | awk '{print $1/$2}')
sell_coin=$(echo "$amount" "$commission" "$rate" | awk '{print $1/$2/$3}')


echo  ""
echo  "+--------+------------------------------+"
date +"| date   | %Y.%m.%d %T UTC%z |"
echo  "+--------+------------------------------+"
echo  "  coin     $coin"
echo  "  rate     $rate eur/$coin"
if [ -n "$rub" ] &&  [ -n "$get" ];
then
  echo "$rub" "$get" "$rate" | awk '{print "  rate     "  $1/$2/$3 " rub/eur"}'
fi
echo  "+        +                              +"
echo  "  rate     $buy_rate eur/$coin"
echo  "  get      $amount eur -> $buy_coin $coin"
echo  "+        +                              +"
echo  "  rate     $sell_rate eur/$coin"
if [ -n "$rub" ] &&  [ -n "$get" ];
then
  echo "$rub" "$get" "$rate" "$commission" | awk '{print "  rate     "  $1/$2/$3/$4 " rub/eur"}'
fi
echo  "  get      $sell_coin $coin -> $amount eur"
echo  "+        +                              +"
