#!/bin/bash

coin=${coin:-LIC}
amount=${amount:-50}

while [ $# -gt 0 ]; do

   if [[ $1 == *"--"* ]]; then
        param="${1/--/}"
        declare "$param"="$2"
   fi

  shift
done

rate=$(curl -s api.bitbase.es/coins/"$coin" | jq '.price')
sell_commission=1.1111111
#buy_commission=1.1111111

date +"date:   %Y.%m.%d"
date +"time:   %T"
echo "coin:   $coin"
echo "rate:   $rate"
echo "$rate" "$sell_commission" | awk '{print "sell:   " $1/$2}'
#echo "$rate" "$sell_commission" | awk '{print "buy:    " $1*$2}'
echo "amount: $amount"

echo "$amount" "$rate" "$sell_commission" | awk '{print "price:  "  $1/$2*$3}'
#echo "$amount" "$rate" "$sell_commission" | awk '{print "price:  "  $1/$2/$3}'